### ISSUE TITLE
Question about "Evaluation Conditions" in paper

### ISSUE THREAD

**Issue by super233** [vikolss/DACS#10]
Hi, thanks for your awesome work. I have noticed that you said "DACS was evaluated as an average of three runs" in "Evaluation Conditions". Dose it mean that the reported result is the average of the best results from three runs? Or dose it mean that the reported result is the average of all results from three runs and each run contains many results?

**Comment by vikolss** [comment]
Each run only has one result, the one from when training is completed after 250k iterations. The reported result is the average of three runs like this. 
This is in contrast to several other works that we are comparing ours against, which actually use early stopping, i.e. report the best result from the course of the training, something we believe is not a fair evaluation.
I hope this answers your question! :)

**Comment by super233** [comment]
Thanks for your reply! :-)
