### ISSUE TITLE
Question about the type of your method

### ISSUE THREAD

**Issue by super233** [vikolss/DACS#11]
Does there exist wamup stage of adversarial training in your method? And is your method only based on self-training? I haven't found the corresponding content in paper so I'm going to ask you.

**Comment by WilhelmT** [comment]
Hi,

Our method does not rely on adversarial learning.

It is only based on self-training, and a very simple variant where the pseudolabels are simply assigned the class of the highest probability, for every pixel, and from uniformly sampling images as usual.

**Comment by super233** [comment]
Thanks for your reply, it's a really an awesome work! 😄
