### ISSUE TITLE
Sucessful reproduce

### ISSUE THREAD

**Issue by ygjwd12345** [vikolss/DACS#12]
wonderful work.
I have successfully reproduced gta2city.
class  0 road         IU 92.93
class  1 sidewalk     IU 52.58
class  2 building     IU 85.81
class  3 wall         IU 27.76
class  4 fence        IU 31.80
class  5 pole         IU 35.65
class  6 traffic_light IU 41.17
class  7 traffic_sign IU 40.13
class  8 vegetation   IU 86.46
class  9 terrain      IU 45.03
class 10 sky          IU 86.32
class 11 person       IU 62.39
class 12 rider        IU 25.00
class 13 car          IU 88.16
class 14 truck        IU 49.78
class 15 bus          IU 54.88
class 16 train        IU 0.00
class 17 motorcycle   IU 35.89
class 18 bicycle      IU 49.64
meanIOU: 0.5217746063564266
Thanks again.

**Comment by WilhelmT** [comment]
Nice to hear, thank you for your interest in our work!
