### ISSUE TITLE
questions about the backbone on vgg16 model

### ISSUE THREAD

**Issue by feipanir** [vikolss/DACS#14]
Hi, thank you for sharing this code.
But I have a question that, have you ever tried running your code on the model with vgg-16 backbone? It seems that it works well on Resnet-101, but when we try it on vgg-16, the performance was dropping. It would be very helpful if you could share some experience. 

Thank you.

**Comment by vikolss** [comment]
Hi,
Unfortunately we did not try using vgg-16 backbone, since most existing works focus on Resnet-101 backbone. So I'm afraid I don't have any insight to share.
Is the performance dropping more here than for other similar works implementing both backbones?

**Comment by feipanir** [comment]
We use a common [ Vgg-16 as backbone](https://github.com/wasidennis/AdaptSegNet/blob/master/model/deeplab_vgg.py) to train on our own dataset. Existing work performance on this dataset is validation mIoU > 30.00. While using DACS,  we observe the val mIoU scores as follows:
Iter_id     Perfermance
5000       mIoU: 19.42
10000      mIoU: 15.68
15000      mIoU: 12.91
20000      mIoU: 12.44
25000      mIoU: 10.95
30000      mIoU: 9.92
35000      mIoU: 10.58
40000      mIoU: 9.51
45000      mIoU: 8.80
50000      mIoU: 7.30
55000      mIoU: 7.89
60000      mIoU: 6.25
65000      mIoU: 7.65
70000      mIoU: 5.44
.....
Still we don't figure out why it is dropping continuously.

Regards,

Fei

**Comment by vikolss** [comment]
I see. I currently don't have the opportunity to conduct these experiments myself, unfortunately.
The performance of DACS is dependent on the distribution of classes in the data, so a possible reason could be that the method is not suitable for the data set that you are using. Have you tried vgg-16 backbone with GTA5/SYNTHIA -> Cityscapes to see if the same thing happens there?

Viktor
