### ISSUE TITLE
can not connect to download the pretrained model

### ISSUE THREAD

**Issue by ywher** [vikolss/DACS#15]
hi, everyone. I have a problem of connecting to http://vllab1.ucmerced.edu/~whung/adv-semi-seg/resnet101COCO-41f33a49.pth to download the pretrained model. Can you give me a help by uploading to google drive?

**Comment by vikolss** [comment]
Thank you for bringing this up!
I am not the owner of that link, and I am also not able to reach it. Did you manage to reach it or find the model elsewhere?

**Comment by ywher** [comment]
> Thank you for bringing this up! I am not the owner of that link, and I am also not able to reach it. Did you manage to reach it or find the model elsewhere?

Sorry, I still can not connect to that URL. But I search the model name 'resnet101COCO-41f33a49.pth' and find the public code 'https://github.com/hb-stone/FC-SOD' also contains the pretrained model of ResNet101 on COCO which is also named resnet101COCO-41f33a49.pth. The link of the model is https://drive.google.com/file/d/1gLiF0yKByduIyD7MEya-4ZI_yp5613Ot/view?usp=sharing. I think they maybe the same, but not so sure.

**Comment by vikolss** [comment]
Ok, nice find. I agree that it seems that they might be the same, they at least have the same architecture. I am unfortunately not able to perform any tests at the moment to see if the performance is the same with this model as with the original one. If you do, please let me know how it went :)

**Comment by ywher** [comment]
> Ok, nice find. I agree that it seems that they might be the same, they at least have the same architecture. I am unfortunately not able to perform any tests at the moment to see if the performance is the same with this model as with the original one. If you do, please let me know how it went :)

I have successfully reproduce the result using this pretrained model.
After training 25k iters:
class  0 road            IU 91.49
class  1 sidewalk     IU 36.92
class  2 building      IU 87.71
class  3 wall         IU 27.02
class  4 fence        IU 38.51
class  5 pole         IU 39.64
class  6 traffic_light IU 43.36
class  7 traffic_sign IU 50.61
class  8 vegetation   IU 87.78
class  9 terrain      IU 40.95
class 10 sky          IU 89.38
class 11 person       IU 65.97
class 12 rider        IU 29.13
class 13 car          IU 90.30
class 14 truck        IU 58.66
class 15 bus          IU 54.12
class 16 train        IU 0.00
class 17 motorcycle   IU 37.28
class 18 bicycle      IU 33.92
meanIOU: 0.527782650365583

**Comment by vikolss** [comment]
That's great! Thank you very much!

**Comment by mkbkxdd** [comment]
> > Ok, nice find. I agree that it seems that they might be the same, they at least have the same architecture. I am unfortunately not able to perform any tests at the moment to see if the performance is the same with this model as with the original one. If you do, please let me know how it went :)
> 
> I have successfully reproduce the result using this pretrained model. After training 25k iters: class 0 road IU 91.49 class 1 sidewalk IU 36.92 class 2 building IU 87.71 class 3 wall IU 27.02 class 4 fence IU 38.51 class 5 pole IU 39.64 class 6 traffic_light IU 43.36 class 7 traffic_sign IU 50.61 class 8 vegetation IU 87.78 class 9 terrain IU 40.95 class 10 sky IU 89.38 class 11 person IU 65.97 class 12 rider IU 29.13 class 13 car IU 90.30 class 14 truck IU 58.66 class 15 bus IU 54.12 class 16 train IU 0.00 class 17 motorcycle IU 37.28 class 18 bicycle IU 33.92 meanIOU: 0.527782650365583

大兄弟 ，我拿作者的模型（miou53）跑出来的结果却是这样的，但我不知道哪里出问题了，你能帮一下我吗，谢谢了
class  0 road         IU 67.69
class  1 sidewalk     IU 9.53
class  2 building     IU 42.74
class  3 wall         IU 3.70
class  4 fence        IU 5.86
class  5 pole         IU 1.79
class  6 traffic_light IU 0.83
class  7 traffic_sign IU 2.28
class  8 vegetation   IU 37.00
class  9 terrain      IU 10.66
class 10 sky          IU 11.93
class 11 person       IU 5.54
class 12 rider        IU 0.38
class 13 car          IU 26.87
class 14 truck        IU 2.51
class 15 bus          IU 5.62
class 16 train        IU 0.00
class 17 motorcycle   IU 3.78
class 18 bicycle      IU 11.55
meanIOU: 0.13172500007111895
