### ISSUE TITLE
Pretrained Models

### ISSUE THREAD

**Issue by chen-hao-chao** [vikolss/DACS#3]
When will you release pretrained models?

Thanks.

**Comment by WilhelmT** [comment]
Will look into it either this week or the next. Leaving the thread open until then!

**Comment by WilhelmT** [comment]
We've trained and commited (link in readme) a pretrained model for GTA. This one ended higher then the reported average. Will try to do one for Synthia as well, but it might take a few weeks due to other current priorities unfortunately.
