### ISSUE TITLE
ImageNet only pretrained Resnet configs

### ISSUE THREAD

**Issue by qinenergy** [vikolss/DACS#5]
Thanks for the amazing code. I tried both GTA2Cityscape and Synthia2Cityscape. Results can be well-reproduced.

May I ask have you tried to use Imagenet-only pretrained weights for the backbone ? Do we need to take care of some special things? 

I tried to use the one used by AdaptSegnet (http://vllab.ucmerced.edu/ytsai/CVPR18/DeepLab_resnet_pretrained_init-f81d91e8.pth) with your default hyper-parameters, but results look weird. I was thinking I missed something.

Thanks in advance!

**Comment by qinenergy** [comment]
There is a mismatch between param names. Sorry for the interruption. Thanks for the code.

**Comment by WilhelmT** [comment]
Hi @qinenergy . We have not tried image-net pretraining, but it sounds like a reasonable thing to test. Please share the results if you are able to :)
