### ISSUE TITLE
The pretrained models  compressed file is corrupted and can not unzip

### ISSUE THREAD

**Issue by Zwl970615** [vikolss/DACS#6]
The ZIP file downloaded from the link to the pretrained models in the README is corrupted and cannot be extracted.Please re-upload a pretrained models files.

**Comment by WilhelmT** [comment]
I have re-uploaded the files. Try it now.

**Comment by Zwl970615** [comment]
Thank you! But the new “Link” require access rights.

**Comment by WilhelmT** [comment]
Ah, I see. Should be fixed now.

**Comment by Zwl970615** [comment]
Thank you very much for your reply! I can download it and unzip it successfully!
