### ISSUE TITLE
Question about the pretrained parameters of backbone

### ISSUE THREAD

**Issue by super233** [vikolss/DACS#7]
Thanks for your contribution for this field and sharing the code.

I notice that you have used backbone that is pretrained on ImageNet or MSCOCO, but it's not clear that the result is of ImageNet or MSCOCO in paper.

Dose there exist much difference between the results of using backbone with different pretrained parameters? If yes, Could you please provide the detailed results of using backbone pretrained on ImageNet and MSCOCO separately?

**Comment by vikolss** [comment]
Thank you for your comment.

The backbone is pretrained on first ImageNet and then MSCOCO, so both.

Unfortunately we do not have the results from using pretraining with only one of the datasets, and it is not possible for me to generate them at this time. I will try to make it happen, but no guarantee.

**Comment by super233** [comment]
Ok, thanks for you reply. :-)
