### ISSUE TITLE
mIoU Scores using Backbones pretrained only on ImageNet instead of ImageNet+MSCOCO?

### ISSUE THREAD

**Issue by ferric123** [vikolss/DACS#9]
Interesting Work! All the methods you compared in the table were using resnet-101 pretrained only on ImageNet, it would be also interesting to know what the mIoU scores of DACS are if trained using the same backbone. Are there any ablation experiments for this? Thanks!

**Comment by WilhelmT** [comment]
Hello. 

We have not performed the experiments ourselves on ImageNet pretraining. However, this has been done as part of another work (see https://github.com/qinenergy/corda/issues/2), where they even found a slight performance increase when rerunning DACS with Imagenet weights.
